# Generated by Django 4.1.6 on 2023-02-26 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_alter_wishlist_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="products",
            new_name="wished_item",
        ),
    ]
