# Generated by Django 4.1.6 on 2023-02-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0003_rename_createdat_wishlist_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="name",
        ),
    ]
