# Generated by Django 4.1.6 on 2023-02-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_address_user_alter_address_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
