# Generated by Django 4.1.6 on 2023-03-05 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_address_city_remove_address_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="account",
        ),
    ]
