# Generated by Django 4.1.6 on 2023-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_account_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=50),
        ),
    ]
