# Generated by Django 4.1.6 on 2023-02-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_brand_alter_variations_product'),
        ('cart', '0003_cartitem_cart_cartitem_user_cartitem_variations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItem', to='products.product'),
        ),
    ]
