# Generated by Django 4.1.6 on 2023-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_coupon_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
