# Generated by Django 4.1.6 on 2023-03-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_addresslinetwo_order_country_order_ordernote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(default='COD', max_length=100),
        ),
    ]
