# Generated by Django 4.1.6 on 2023-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_paymentmethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="productPrice",
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
