# Generated by Django 4.1.6 on 2023-03-05 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_remove_orderproduct_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="Payment",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="product",
        ),
    ]
