# Generated by Django 4.1.6 on 2023-02-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='variationName',
            new_name='variationValue',
        ),
    ]
