# Generated by Django 4.1.6 on 2023-02-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[
                    ("adidas", "Adidas"),
                    ("nike", "Nike"),
                    ("reebok", "Reebok"),
                    ("redchief", "Redchief"),
                    ("seeandwear", "See and wear"),
                    ("uspolo", "US Polo"),
                    ("leecooper", "Lee Cooper"),
                    ("campus", "Campus"),
                    ("bata", "Bata"),
                    ("crocs", "Crocs"),
                    ("mactree", "Mactree"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="variations",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="products.product",
            ),
        ),
    ]
