# Generated by Django 4.1.6 on 2023-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "prodcut gallery",
            },
        ),
    ]
